wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.1
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
batch_size:
  desc: null
  value: 64
eps:
  desc: null
  value: 1.0
eps_decay:
  desc: null
  value: 0.99995
eps_min:
  desc: null
  value: 0.05
gamma:
  desc: null
  value: 0.99
lr:
  desc: null
  value: 0.001
